import { ChainID, ChainURL } from "@/types";
import {
  GOERLI_SUBGRAPH_URL,
  MAINNET_SUBGRAPH_URL,
  UNISWAP_GOERLI_SUBGRAPH_URL,
  UNISWAP_MAINNET_SUBGRAPH_URL,
} from "./env";

export const SUBGRAPH_URL: ChainURL = {
  [ChainID.METIS]: MAINNET_SUBGRAPH_URL,
  [ChainID.GOERLI]: GOERLI_SUBGRAPH_URL,
};

export const UNISWAP_SUBGRAPH_URL: ChainURL = {
  [ChainID.METIS]: UNISWAP_MAINNET_SUBGRAPH_URL,
  [ChainID.GOERLI]: UNISWAP_GOERLI_SUBGRAPH_URL,
};
